(package "sublime-fuzzy"
         "0.1.0"
         "Fuzzy matching algorithm like Sublime Text's string search")

(website-url "https://github.com/jcs-elpa/sublime-fuzzy")
(keywords "sublime" "fuzzy" "algorithm")

(package-file "sublime-fuzzy.el")

(source "melpa")

(depends-on "emacs" "25.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
